export enum DIFFICULT_LEVELS {
	HARD = 'HARD',
	MEDIUM = 'MEDIUM',
	EASY = 'EASY'
}

export const MEAL_CATEGORIES = [
	'BREAKFAST',
	'LUNCH',
	'BRUNCH',
	'DINNER',
	'BURGER',
	'SALAD',
	'SOUP',
	'APPETIZER',
	'DESSERT',
	'HOTPOT',
	'NORTH_VN',
	'CENTRAL_VN',
	'SOUTH_VN'
];

export const INGREDIENT_CATEGORIES = [
	'MILK AND DAIRY',
	'GRAINS',
	'BEVERAGES NONALCOHOLIC',
	'PROTEIN_FOODS',
	'SNACKS AND SWEETS',
	'ALCOHOLIC BEVERAGES',
	'WATER',
	'FATS AND OILS',
	'MIXED DISHES',
	'FRUIT',
	'CONDIMENTS AND SAUCES',
	'SUGARS',
	'VEGETABLES',
	'INFANT FORMULA AND BABY FOOD',
	'OTHER'
];
